### ISSUE TITLE
runtime: failed to create new OS thread (have 2 already; errno=22)

### ISSUE THREAD

**Issue by SanthoshSiddegowda** [WendellAdriel/laravel-exa#2]
Getting issue while running on the Mac M1 chip

```
santosh.js@192 laravel-exa % make configure        
cp .env.example .env \
	&& make install \
	&& make art ARGS="key:generate --ansi"
docker compose run --rm app composer install
WARN[0000] Found orphan containers ([laravel-exa-redis laravel-exa-mailpit]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 1/0
 ⠿ Container laravel-exa-db  Created                                                                                                                                                0.0s
[+] Running 1/1
 ⠿ Container laravel-exa-db  Started                                                                                                                                                0.3s
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x6430dc, 0x9)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc42002c000, 0xc42003c000)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0x650dd0, 0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1628 +0x137
runtime.main.func1()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x75bb00)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:281 fp=0xc420028788 sp=0xc420028780
runtime.main()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:127 +0x6c fp=0xc4200287e0 sp=0xc420028788
runtime.goexit()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200287e8 sp=0xc4200287e0
make[1]: *** [install] Error 2
make: *** [configure] Error 2
```

**Comment by SanthoshSiddegowda** [comment]
solved temporarily by this solution
https://stackoverflow.com/a/69915286

**Comment by WendellAdriel** [comment]
@SanthoshSiddegowda can you please check if this is fixed in v1.2.0?

**Comment by WendellAdriel** [comment]
@SanthoshSiddegowda were you able to check?

**Comment by SanthoshSiddegowda** [comment]
@WendellAdriel sorry for the delay. let me try tonight IST.

**Comment by SanthoshSiddegowda** [comment]
Awesome. Issue solved in the latest version of  [v1.3.0](https://github.com/WendellAdriel/laravel-exa/releases/tag/v1.3.0)

**Comment by WendellAdriel** [comment]
@SanthoshSiddegowda thanks for checking that!!! 😉

**Comment by SanthoshSiddegowda** [comment]
@WendellAdriel Thanks the laravel-exa !! 😉 👏
